export const GETDOCTORREQ = "GETDOCTORREQ";
export const GETDOCTORSUCESS = "GETDOCTORSUCESS";
export const GETDOCTORFAILURE = "GETDOCTORFAILURE";

export const GETSINGLEDOCTORREQ = "GETSINGLEDOCTORREQ";
export const GETSINGLEDOCTORSUCESS = "GETSINGLEDOCTORSUCESS";
export const GETSINGLEDOCTORFAILURE = "GETSINGLEDOCTORFAILURE";

export const GETROOMREQ = "GETROOMREQ";
export const GETROOMSUCESS = "GETROOMSUCESS";
export const GETROOMFAILURE = "GETROOMFAILURE";


export const GETSPECILITYDATAREQ     = "GETSPECILITYDATAREQ";
export const GETSPECILITYDATASUCESS  = "GETSPECILITYDATASUCESS";
export const GETSPECILITYDATAFAILURE = "GETSPECILITYDATAFAILURE";

export const ADDTOCARTREQ     = "ADDTOCARTREQ";
export const ADDTOCARTSUCESS  = "ADDTOCARTSUCESS";
export const ADDTOCARTFAILURE = "ADDTOCARTFAILURE";


export const GETCARTREQ     = "GETCARTREQ";
export const GETCARTSUCESS  = "GETCARTSUCESS";
export const GETCARTFAILURE = "GETCARTFAILURE";


export const DELETECARTITEMREQ     = "DELETECARTITEMREQ";
export const DELETECARTITEMSUCESS  = "DELETECARTITEMSUCESS";
export const DELETECARTITEMFAILURE = "DELETECARTITEMFAILURE";

