
export const GETDOCTORREQ = "GETDOCTORREQ"
export const GETDOCTORSUCESS = "GETDOCTORSUCESS"
export const GETDOCTORFAILURE = "GETDOCTORFAILURE"

export const GETSINGLEDOCTORREQ = "GETSINGLEDOCTORREQ"
export const GETSINGLEDOCTORSUCESS = "GETSINGLEDOCTORSUCESS"
export const GETSINGLEDOCTORFAILURE = "GETSINGLEDOCTORFAILURE"
