export const LOGINUSERREQ = "LOGINUSERREQ";
export const LOGINUSERSUCESS = "LOGINUSERSUCESS";
export const LOGINUSERFAILURE = "LOGINUSERFAILURE";


export const SINGUPUSERREQ = "SINGUPUSERREQ";
export const SINGUPUSERSUCESS = "SINGUPUSERSUCESS";
export const SINGUPUSERFAILURE = "SINGUPUSERFAILURE";